# Generated by Django 4.1.3 on 2022-11-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(null=True)),
                ('artist_id', models.CharField(max_length=15)),
                ('work_url_100', models.URLField(null=True)),
            ],
        ),
    ]
