# Generated by Django 4.1.3 on 2022-11-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField()),
                ('url', models.URLField(null=True)),
                ('artis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artis.artis')),
            ],
        ),
    ]
