# Generated by Django 4.1.3 on 2022-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='songs_genres', to='genres.genres'),
        ),
    ]
