# Generated by Django 4.1.3 on 2022-11-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='genres',
            field=models.ManyToManyField(to='genres.genres'),
        ),
    ]
