# Generated by Django 4.1.3 on 2022-11-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artis', '0001_initial'),
        ('songs', '0002_alter_songs_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artis.artis'),
        ),
    ]
