# Generated by Django 4.1.3 on 2022-11-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_songs_artis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
