# Generated by Django 4.1.3 on 2022-11-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artis', '0001_initial'),
        ('genres', '0001_initial'),
        ('songs', '0003_alter_songs_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artis', to='artis.artis'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='genres.genres'),
        ),
    ]
